import React from "react";
import { motion } from "framer-motion";
const SampleBook = () => {
    const data = [
        {
            title: "Science Fiction",
            image: "https://raw.githubusercontent.com/adarshagupta/trybookai/main/public-assets/paradox.png",
            description:
                "As Dr. Elara stepped through the shimmering portal, she knew there was no turning back. The fate of two universes now rested in her hands...",
        },
        {
            title: "Mystery",
            image: "https://raw.githubusercontent.com/adarshagupta/trybookai/main/public-assets/mist.png",
            description:
                "The old lighthouse stood silent, its beacon long extinguished. But on foggy nights, some swore they could still see its ghostly light...",
        },
        {
            title: "Fantasy",
            image: "	https://raw.githubusercontent.com/adarshagupta/trybookai/main/public-assets/ecos.png",
            description:
                "The ancient prophecy spoke of a child born with starlight in their eyes. As the comet blazed overhead, the kingdom held its breath...",
        },
    ];
    return (
        <div className=" max-w-[1100px] mb-12 mx-auto">
            <div className="mt-24 text-3xl font-semibold text-center dark:text-gray-100">
                <h1>Sample Books Generated by BookAI</h1>
                <h3 className="mt-4 text-lg ">
                    Explore some of the captivating books created using our AI technology
                </h3>
            </div>
            <div className="flex flex-wrap mt-12 md:flex-nowrap md:gap-x-8">
                {data.map((item, index) => (
                    <motion.div
                        whileHover={{
                            y: -8,
                            transition: { duration: 0.2 },
                            spring: { type: "spring", stiffness: 300, damping: 30 },
                        }}
                        key={index}
                        className="relative md:max-w-[400px] max-w-[380px] flex flex-col items-center justify-center p-4 mx-auto mt-12 bg-gray-600 bg-opacity-10 dark:bg-[rgba(255,_255,_255,_0.05)]dark:bg-opacity-20 rounded-xl">
                        <div className="relative object-fill h-[300px] w-[200px]  ">
                            <img src={item.image} alt="" />
                        </div>
                        <h3 className="mt-8 text-xl font-bold dark:text-white">{item.title}</h3>
                        <p className="mt-2 text-center text-gray-700 dark:text-white">
                            "{item.description}"
                        </p>
                        <button className="mt-4 text-xl font-bold text-violet-900 w-fit">
                            Read more
                        </button>
                    </motion.div>
                ))}
            </div>
        </div>
    );
};

export default SampleBook;
